export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERRORS = 'LOGOUT_ERRORS';


//STAFF DISPATCH
export const STAFF_LOADING = 'STAFF_LOADING';
export const STAFF = 'STAFF';

//PRODUCTS DISPATCH 
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const FIND_PRODUCTS = 'FIND_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';


//ROOMS DISPATCH
export const SELECT_ROOM = 'SELECT_ROOM';
export const ENTER_CHAT_ROOM = 'ENTER_CHAT_ROOM';