# Generated by Django 3.2 on 2021-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('secondName', models.CharField(max_length=200)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
    ]
