# Generated by Django 3.2 on 2021-04-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=50)),
                ('suppilerAddress', models.CharField(max_length=100)),
                ('supplierPostcode', models.CharField(max_length=7)),
                ('supplierEmail', models.EmailField(max_length=254)),
                ('supplierContactName', models.CharField(max_length=50)),
                ('supplierCode', models.CharField(max_length=5)),
                ('supplierCountry', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024)),
                ('available', models.BooleanField(default=False)),
                ('barcode', models.CharField(max_length=52)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backendapp.productgroup')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('brandSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.supplier')),
            ],
        ),
    ]
